### PR TITLE
Bump django from 2.2.13 to 3.1.2

### LINKED ISSUE #11: fix: Audit requirements.txt
The django_todo project should be migrated from Django 2.x to 3.x

### PR DESCRIPTION
**Pull request by saravananselvamohan**
Fix #11

### CODE REVIEW

**Comment by Aju100** [comment]
@saravananselvamohan  what about code file

**Comment by saravananselvamohan** [comment]
@Aju100 . I am not sure about other changes. Would you guide me the other changes please.

**Comment by Aju100** [comment]
@saravananselvamohan django 3.x has asgi.py and new updates in their structure.

**Comment by saravananselvamohan** [comment]
> @saravananselvamohan django 3.x has asgi.py and new updates in their structure.

@Aju100 . Thanks for the suggestion and made the changes. Would like review and suggest further changes as Iam completely new to django

**Comment by Aju100** [comment]
@saravananselvamohan u have change the file name. my issue was about to change whole the code based structure from 2.x to 3.x

**Pull request closed without merging**
